function [ models ] = getStrokeGestureModels()
% 免训练笔画手势模型定义/No training stroke gesture model definition
% condition 状态定义: ['field', 'action', 'threshold']
%                    Action
%                       options: '>', '<', '|>|', '|<|', 'convex', 'concave', 'angle28'
%                    Threshold
%                       options: number or axis: 'x', 'y', 'z'
    models = [...
        struct('id', 1, 'gesture', 'right-arc', 'conditions', [...
            struct('field', 'yGyroData', 'action', '<', 'threshold', -5),...
            struct('field', 'zGyroData', 'action', 'concave', 'threshold', -10),...
        ]),...
        struct('id', 2, 'gesture', 'left-arc', 'conditions', [...
            struct('field', 'yGyroData', 'action', '<', 'threshold', -5),...
            struct('field', 'zGyroData', 'action', 'convex', 'threshold', 8),...
        ]),...
        struct('id', 3, 'gesture', 'left-down', 'conditions', [...
            struct('field', 'yGyroData', 'action', '<', 'threshold', -10),...
            struct('field', 'zGyroData', 'action', '|<|', 'threshold', 'y'),...
            struct('field', 'zGyroData', 'action', '>', 'threshold', 3),...
        ]),...
        struct('id', 4, 'gesture', 'right-down', 'conditions', [...
            struct('field', 'yGyroData', 'action', '<', 'threshold', -6),...
            struct('field', 'zGyroData', 'action', '<', 'threshold', -10),...
            struct('field', 'yGyroData', 'action', 'angle12', 'threshold', 'z'),...
            struct('field', 'zGyroData', 'action', 'angle28', 'threshold', 'y'),...
        ]),...
        struct('id', 5, 'gesture', 'down', 'conditions', [...
            struct('field', 'yGyroData', 'action', '<', 'threshold', -10),...
            struct('field', 'zGyroData', 'action', '|<|', 'threshold', 'y'),...
            struct('field', 'zGyroData', 'action', '>', 'threshold', 'y'),...
        ]),...
        struct('id', 6, 'gesture', 'right', 'conditions', [...
            struct('field', 'yGyroData', 'action', '>', 'threshold', 'z'),...
            struct('field', 'yGyroData', 'action', '|<|', 'threshold', 'z'),...
            struct('field', 'zGyroData', 'action', '<', 'threshold', -10),...
        ]),...
        struct('id', 7, 'gesture', 'rotate', 'conditions', [...
            struct('field', 'xGyroData', 'action', 'concave', 'threshold', -40),...
        ]),...
    ];

end

